Appointment type class with CRUD operations
ChronoSync24/chronosync-be pull request #3
Opened 2024-11-17 19:19 UTC by riadims

Appointment type class create alongiside controller, service, config and DTO classes.

2024-11-18 12:24 UTC, kfejzic1 requested changes

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/model/appointmentType/AppointmentType.java
> +@Table(name = "appointmentType")
table name should be in plural

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/model/appointmentType/AppointmentType.java
> +
As I remember, appointment types should have relationship with firm. Implement it.

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/model/appointmentType/AppointmentType.java
> +
color attribute is missing

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +public class AppointmentTypeServiceImpl {
what does it implement? where is appointment type service interface?

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +	public AppointmentTypeServiceImpl(AppointmentTypeRepository appointmentTypeRepository) {
@AllArgsConstructor

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +	 * @return {@link List} of {@link AppointmentType} containing all appointment types
javadocs formatting

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		return appointmentTypeRepository.findAll();
Same comment about this like the one for endpoint using method. This is too risky, filtering and pagination should be implemented

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +	public AppointmentType createAppointmentType(AppointmentTypeRequestDTO requestDTO) {
parameter name requestDto

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +	private AppointmentType mapRequestToModel(AppointmentTypeRequestDTO requestDTO) {
This method does not have any relation with AppointmentTypeService. Extract it to AppointmentTypeRequestDTO, and create method toModel. You can check UserRegisterRequestDTO.java. Use filter builder pattern for it.

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		if (!appointmentTypeRepository.existsById(id)) {
Argument exceptions should be thrown from controllers. Services throw ServiceException

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		appointmentTypeRepository.deleteById(id);
Repository should throw exception if id does not exist in database. Check that exception here and pass it as ServiceException. There is no need for checking existsById

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +			throw new IllegalArgumentException("Appointment type with ID " + id + " does not exist.");
IllegalArgumentException should be thrown from controller, services throw ServiceException.

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		return appointmentTypeRepository.save(appointmentType);
What happens when you call save before checking for existence in the database? If save throws repository exception, which it should, catch that exception and pass it as ServiceException. There is no need for additional existence checking in the database,

2024-11-18 12:24 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		AppointmentType appointmentType = optionalAppointmentType.get();
Use toModel

2024-11-21 10:27 UTC, kfejzic1 requested changes
Please watch out for the same mistakes from the first review. The goal is to not repeat mistakes after each review.

After you have done with changes, please format every document that is changed using intellij's built in code formatter. Ask for its' configuration when you are done with the changes.

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/AppointmentTypeRepository.java
> - *  AppointmentType repository class for managing appointment types.
Why is javadocs deleted?

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/AppointmentTypeRepository.java
> +	// Custom query to find appointment types by firm ID
this is not javadocs

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/AppointmentTypeRepository.java
> +	List<AppointmentType> findByFirm_Id(Long id);
Any filtering should be done using JpaRepository's method findOne if one entity is expetded as return is expected and find if collection of them is expected. For its' usage implement FirmFilterBuilder.

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/FirmRepository.java
> +public interface FirmRepository extends JpaRepository<Firm, Long> {
javadocs

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/UserRepository.java
> +	 * @return {@link Optional} containing the {@link User} if found, empty otherwise
What Optional? Optional is wrapper, same as ResponseEntity. Function returns:
```
Optional<User>
```

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/AppointmentTypeService.java
> +
remove line

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/AppointmentTypeService.java
> +	List<AppointmentType> getAppointmentTypesByFirmId(Long id);
Filtering should be done using find or findOne

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/AppointmentTypeService.java
> +public interface AppointmentTypeService {
Javadocs

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		return appointmentTypeRepository.findByFirm_Id(id);
filter using findOne and filter builders

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		} catch (Exception e) {
Catching Exception class is antipattern. Any exception that is thrown in previous code will be catched here and passed as a service exception which could not be the case. Additionaly, is this try catch necessary? Service exceptions are already thrown when user is not found and if he is not associated with any firm.

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +			User user = userRepository.findByUsername(username)
filter using findOne

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/UserRepository.java
> +	Optional<User> findByUsername(String username);
Does this method already exists in JpaRepository? If not, implement it using findOne and filtering logic

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/dto/request/AppointmentTypeRequestDTO.java
> +
Firm attribute

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +			AppointmentType existingAppointmentType = appointmentTypeRepository.findById(id)
Why do you need to retrieve appointment type from db? You already have id. Use Firm from AppointmentTypeRequestDto.

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		} catch (Exception e) {
Same comment abut exception as before. Do we need this try catch block?

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		} catch (Exception e) {
same comment as before

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		} catch (EmptyResultDataAccessException e) {
why this exception?

2024-11-21 10:27 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/UserServiceImpl.java
> +@AllArgsConstructor
Why is this changed?

2024-11-21 18:45 UTC, riadims commented on src/main/java/com/sinergy/chronosync/service/impl/UserServiceImpl.java
> +@AllArgsConstructor
Probably mistaken during coding, change reverted

2024-11-21 18:52 UTC, riadims commented on src/main/java/com/sinergy/chronosync/model/appointmentType/AppointmentType.java
> +	@JsonBackReference
When a GET request is sent to display appointmentTypes of a certain user an infinite loop is created, appointmentType data contains firm_id which then again returns appointmentTypes of that firm and so on.

2024-11-21 20:05 UTC, riadims commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		return appointmentTypeRepository.findByFirm_Id(id);
findOne is used for retrieving single entities, findBy is best for fetching all appTypes associated with the specific firm

2024-11-21 20:18 UTC, riadims commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +		} catch (EmptyResultDataAccessException e) {
Thrown when trying to delete an entity that doesn't exist, after reviewing and further investigation it is understood that the Spring Data JPA already does that and the method is changed.

2024-11-26 23:02 UTC, kfejzic1 requested changes
Comments, functions and any code related to users should not be dependant on any user type. Please avoid relating user types with certain functions or any code. WebSecurityConfig class should map everything that is needed for the roles.

2024-12-03 18:11 UTC, riadims commented on src/main/java/com/sinergy/chronosync/controller/AppointmentTypeController.java
> +		List<AppointmentType> appointmentTypes = appointmentTypeServiceImpl.getAppointmentTypesForCurrentUser();
This endpoint is intended for users associated with a firm to view the appointment types specific to their firm. It ensures data isolation by returning only the appointment types linked to the logged-in user's firm

Comment added to javadocs as well

2024-12-24 18:54 UTC, kfejzic1 requested changes
Please once more review unused imports and formatting, pay attention to the line endings. 

Writing unit tests should have high coverage (aim is >90%). Also please use this method to revise your unit tests implementation.

Additionally, the use of AI tools is a convenience and should be employed but with a dose of caution. You should thoroughly understand what is happening behind the written code, and why it is written like that.

Overall, this looks nice.

2024-12-24 18:54 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/AppointmentTypeRepository.java
> +public interface AppointmentTypeRepository extends JpaRepository<AppointmentType, Long>, JpaSpecificationExecutor<AppointmentType> {
line too long

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/builder/AppointmentTypeFilterBuilderTest.java
> +public class AppointmentTypeFilterBuilderTest {
Javadocs

2024-12-24 18:54 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/model/firm/Firm.java
> +public class Firm extends BaseEntity {
javadocs

2024-12-24 18:54 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/repository/UserRepository.java
> -
revert this change

2024-12-24 18:54 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/UserServiceImpl.java
> -
Revert this change

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/controller/AppointmentTypeControllerTest.java
> +		AppointmentType appointmentType = new AppointmentType();
Assign some attributes to this variable. You can create private method that returns some dummy object of appointmentType if it can be reuse in other tests.

2024-12-24 18:54 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/controller/AppointmentTypeController.java
> +		@RequestParam(defaultValue = "10") int size
Also this should be renamed to pageSize, since size is too vague

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/repository/AppointmentTypeRepositoryTest.java
> +class AppointmentTypeRepositoryTest {
javadocs

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/repository/AppointmentTypeRepositoryTest.java
> +		assertThat(result).hasSize(appointmentTypes.size());
This test does not differ from previous one. You provided name "Consultation" in type filter builder. Assert that this name is in returned list. You can use dummy appointment type class for it.

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/repository/AppointmentTypeRepositoryTest.java
> +			.thenReturn(java.util.Optional.of(appointmentType));
Import java.util.Optional, then use Optional.of()

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/service/AppointmentTypeServiceTest.java
> +	void getAppointmentTypesForUser_ValidUser_ReturnsPageOfAppointmentTypes() {
naming convenience

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/service/AppointmentTypeServiceTest.java
> +	void getAppointmentTypesForUser_UserNotFound_ThrowsException() {
naming

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/service/AppointmentTypeServiceTest.java
> +	void createAppointmentType_ValidRequest_CreatesAppointmentType() {
naming

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/service/AppointmentTypeServiceTest.java
> +		Firm mockFirm = new Firm();
This code is repeating. Extract it to private function.

2024-12-24 18:54 UTC, kfejzic1 commented on src/test/java/com/sinergy/chronosync/service/AppointmentTypeServiceTest.java
> +	}
Missing tests for deleting, updating and valid/invalid filtering.

2024-12-24 18:54 UTC, kfejzic1 commented on src/main/java/com/sinergy/chronosync/service/impl/AppointmentTypeServiceImpl.java
> +	public Page<AppointmentType> getAppointmentTypesForUser(int page, int size) {
This function should be renamed to ```getUserAppointmentTypes```. Rename any of its usages and comment appearances (use refactoring).

2025-01-08 20:47 UTC, kfejzic1 approved these changes

2025-01-08 20:47 UTC, merged

2025-01-10 17:14 UTC, riadims reviewed
.